#!/usr/bin/env python

import sys

import datetime
import requests


# Windows does not support another method
epoch = datetime.datetime.utcfromtimestamp(0)  
def unix_time(dt):
    return int((dt - epoch).total_seconds()) - 7200


def print_menu(menu):
    print('\n\033[1m{} \033[34m{}\033[0m'.format(menu['title'], menu['price']))

    for item in menu['menu']:
        print(' - ' + item)

if len(sys.argv) == 1:
    location = input('Location: ')
else:
    location = sys.argv[1]

data = requests.get('https://themachine.jeremystucki.com/api/v1/coop/menus/{}'.format(location))
current_day = unix_time(datetime.datetime.combine(datetime.datetime.now().date(), datetime.time()))
print(current_day)

for menu in data.json()['results']:
    if menu['timestamp'] == current_day:
        if len(sys.argv) < 3 or (len(sys.argv) == 3 and sys.argv[2] == menu['title']):
            print_menu(menu)

print()
